% Wrapper function for Gillespie's Algorithm with a piecewise-constant
% rate constant. 

function [X, t, r, G] = SimulateSSA_TV(X0, c, Pre,...
                    Post, N, T, tvRateIndex, params, ...
                    syncTime, startTime)

     [X, t, r, G] = SimulateMarginalProcess(X0, c, Pre,...
        Post, N, T, tvRateIndex, ...
        params.inputTimes, params.inputLevels, ...
        [syncTime], ...
        startTime, [], [], [], [], []);
end